name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'  # Habilitar caché para npm

    - name: Install Make
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Install dependencies
      run: make setup

    - name: Run linter
      run: make lint

    - name: Run tests
      run: make test

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Utilizar el secret SNYK_TOKEN
